name: iOS Custom Cloud Build

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    name: Build for 体当たりゲーム
    runs-on: macos-14

    steps:
      - name: Checkout
        uses: actions/checkout@v5 # 先ほどのNode警告対策でv5にアップデート

      - name: Set up Xcode version
        run: sudo xcode-select -s /Applications/Xcode_15.4.app

      - name: Install CocoaPods
        run: |
          pod install

      # 「build-for-testing」を「build」に変更し、テスト処理をスキップ
      - name: Build Application
        run: |
          xcodebuild build \
                     -workspace "体当たりゲーム.xcworkspace" \
                     -scheme "体当たりゲーム" \
                     -sdk iphonesimulator \
                     CODE_SIGNING_ALLOWED=NO \
                     CODE_SIGNING_REQUIRED=NO
