      - name: Install CocoaPods
        run: |
          pod install

      # 👇 ここから追加：最新のXcodeに対応させるための自動修正スクリプト
      - name: Fix Pods Compatibility for modern Xcode
        run: |
          sed -i '' 's/IPHONEOS_DEPLOYMENT_TARGET = 9.0/IPHONEOS_DEPLOYMENT_TARGET = 13.0/g' 体当たりゲーム.xcodeproj/project.pbxproj || true
          pod repo update --verbose || true

      - name: Build Application
        run: |
          xcodebuild build \
                     -workspace "体当たりゲーム.xcworkspace" \
                     -scheme "体当たりゲーム" \
                     -sdk iphonesimulator \
                     CODE_SIGNING_ALLOWED=NO \
                     CODE_SIGNING_REQUIRED=NO
